function net = trainCNN(XTrain, YTrain, layers)
    options = trainingOptions('adam', ...
        'MaxEpochs', 20, ...
        'MiniBatchSize', 32, ...
        'InitialLearnRate', 0.001, ...
        'Verbose', false, ...
        'Plots', 'training-progress');
    net = trainNetwork(XTrain, YTrain, layers, options);
end